import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Game from './game/index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gordle</title>
        <meta name="green wordle in english and portuguese" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Game />
    </div>
  )
}
